# DISCLAIMER: 
# This code was previously part of Joris Heemskerks Bachelors thesis, 
# and is being re-used here. All rights are reserved to Joris Heemskerk, 
# and Technolution BV, Gouda NL. Joris was granted the rights to use and 
# modify this code, at the express notion that a disclaimer was put in.

# Default environment yaml file
# NOTE: See config/config_validation_template.py for the 
# parameter restrictions.

general:
    num_data_workers: 4 # Number of workers preparing batches, set to 0 if you get memory issues.
jobs:
    job0:
        ### Data ###
        sample_rate: [22050]
        stride: [32] # seconds
        duration: [3] # seconds
        n_fft: [1024]
        hop_length: [256]
        n_mels: [80]
        top_db: [80]
        train_val_split: [.8, .2] # Only used if k_folds == 1
        batch_size: [8]
        ### Model ###
        model: "resnet18" # Can be from: [resnet18, all]
        model_params: # Contents depend on the model used
            this_cant_be_empty_aparently: 69420
        optimiser: "adam"
        learning_rate: [0.0001]
        weight_decay: [0.0001]
        n_epochs: 20
        k_folds: 1  # use 1 to ignore
        ## Tune ###
        tune: false
        n_trials: 15
        n_startup_trials: 5
